[toolchain]
anchor_version = "0.31.1"
solana_version = "2.1.21"
package_manager = "yarn"

[features]
resolution = false
skip-lint = false

[programs.localnet]
governo = "gov3LSmekCKmzLnKJ87csYdef5QNYM2G3kNDbhZekkA"
rewarder = "rev31KMq4qzt1y1iw926p694MHVVWT57caQrsHLFA4x"
vesto = "1ok3Ge8vXYPeQgwJd5GBQZkXqW34TbpkvP1APiDVtUF"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[workspace]
types = "packages/sdk/src/generated/"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 100000
shutdown_wait = 2000
upgradeable = false
