[package]
name = "governo"
version = "0.11.0"
description = "Created with Anchor"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "governo"

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]

[dependencies]
anchor-lang = { workspace = true }
anchor-spl = { workspace = true }
anchor-common = { workspace = true }
math = { workspace = true }

rewarder = { path = "../rewarder", features = ["cpi"] }
spl-governance = { git = "https://github.com/stabbleorg/spl-governance-cpi", rev = "da8a54565ff43280ebe2ac7a4a3a6f5eb7ecc070" }
