[package]
name = "governo"
version = "0.13.0"
description = "Created with Anchor"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "governo"

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]

[dependencies]
anchor-lang = { workspace = true }
anchor-spl = { workspace = true }
anchor-common = { workspace = true }
math = { workspace = true }

rewarder = { path = "../rewarder", features = ["cpi"] }
spl-governance-anchor = { git = "https://github.com/stabbleorg/spl-governance-anchor", rev = "9a62593dc9aa71cea9aab2f85596a267072726b0" }
